version: 0.2
env:
  parameter-store:
    DB_Name: /CodeBuild/EKANSH_DB_NAME
    UserName: /CodeBuild/EKANSH_USER_NAME
    Password: /CodeBuild/EKANSH_PASS
    Host: /CodeBuild/EKANSH_ENDPOINT
phases:
    build:
       commands:
         - sed -i 's/database_name_here/'$DB_Name'/' wordpress/wp-config.php 
         - sed -i 's/username_here/'$UserName'/' wordpress/wp-config.php
         - sed -i 's/password_here/'$Password'/' wordpress/wp-config.php
         - sed -i 's/localhost/'$Host'/' wordpress/wp-config.php
artifacts:
  files:
    - '**/*'
